export const allFeatured = [
  {
    title: 'Tukso',
    category: 'Film',
    subcategory: 'Cinemalaya',
    description:
      'A young village lass is found dead. An investigator (Adel) is assigned to look into the case and gets to learn more about the girl and the people whose lives have been affected by her and her death: her father (Bal), a young architect (Carlo), a businessman (David), her childhood friend (Emer), and a widow (Fe).',
    footage: '',
    poster: 'Thumbnails/Tukso/Poster.png',
    banner: 'Thumbnails/Tukso/Banner.png',
    teaser: 'Thumbnails/Anak Ka Ng/Pingkian_ Isang Musikal.mp4',
    resolution: '720p',
    runtime: '1 hr 16 mins',
  },
  {
    title: 'Vox Populi',
    category: 'Film',
    subcategory: 'Cinemalaya',
    description:
      'Vox Populi follows a female candidate for mayor in a small town on the last day of the campaign period. To ensure her win, she will need to secure the support of voters and financiers who may have varying, and even conflicting, desires and agendas.',
    footage: '',
    poster: 'Thumbnails/Vox Populi/Poster.png',
    banner: 'Thumbnails/Vox Populi/Banner.png',
    teaser: 'Thumbnails/Anak Ka Ng/Pingkian_ Isang Musikal.mp4',
    resolution: '720p',
    runtime: '1 hr 26 mins',
  },
  {
    title: 'Backstage Pass: Life Behind the Curtains',
    category: 'Film',
    subcategory: '',
    description:
      'Directed by award-winning indie filmmaker Joseph Mangat, this 30-minute feature documentary covers the back-of-house activities of the CCP Theater Crew in lights, fly, and stage areas. Featured crew members likewise share their unique backstage stories in the film.',
    footage: '',
    poster: 'Thumbnails/Backstage Pass_ Life Behind the Curtains (Episode 1)/Poster.png',
    banner: 'Thumbnails/Backstage Pass_ Life Behind the Curtains (Episode 1)/Banner.png',
    teaser: '',
    resolution: '4K',
    runtime: '29 mins',
  },
  {
    title: 'Backstage Pass: A Portrait of a Scenic Artist',
    category: 'Film',
    subcategory: '',
    description:
      'Directed by award-winning indie filmmaker Joseph Mangat, this 30-minute feature documentary follows the day in the life of a scenic draftsman, model maker, and painter. This documentary focuses on the numerous productions that he has done and the mentees that he has mentored in the past years since the 1970s.',
    footage: '',
    poster: 'Thumbnails/Backstage Pass_ A Portrait of a Scenic Artist (Episode 2)/Poster.png',
    banner: 'Thumbnails/Backstage Pass_ A Portrait of a Scenic Artist (Episode 2)/Banner.png',
    teaser: '',
    resolution: '1920p',
    runtime: '31 mins',
  },
  {
    title: 'Mga Eksena sa Buhay ng Kontrabida',
    category: 'Theater',
    subcategory: 'VLF',
    description:
      'Jake is a villain. He’s violent, selfish, and reckless. Unfortunately, Jake doesn’t exist in a vacuum, and his behavior has consequences. Because Jake is a villain, people around him feel threatened, and these people look for ways to solve the problem that is Jake. Part origin story, part family drama, the play is a collection of conversations heard in the vicinity of a villain.',
    footage: '',
    poster: 'Thumbnails/Mga Eksena sa Buhay ng Kontrabida/Poster.png',
    banner: 'Thumbnails/Mga Eksena sa Buhay ng Kontrabida/Banner.png',
    teaser: '',
    resolution: '1080p',
    runtime: '52 mins',
  },
  {
    title: 'Noli Me Tangere: The TeleMovie (Episode 1: Crisostomo Ibarra)',
    category: 'CCP Specials',
    subcategory: '',
    description:
      "Eddie Romero's Noli Me Tangere mini-series, a faithful rendition of Rizal's characters and their respective tales.",
    footage: '',
    poster: 'Thumbnails/Noli Me Tangere_ The TeleMovie (Episode 1 - Crisostomo Ibarra)/Poster.png',
    banner: 'Thumbnails/Noli Me Tangere_ The TeleMovie (Episode 1 - Crisostomo Ibarra)/Banner.png',
    teaser: '',
    resolution: '720p',
    runtime: '49 mins',
  },
  {
    title: 'Doc Resureccion: Gagamutin ang Bayan',
    category: 'Theater',
    subcategory: '',
    description:
      "Dr. Jess Resureccion is running for mayor in his poor fishing village, determined to bring real change to the place he grew up in. However, Dr. Jess’ cousin, Boy Pogi Resureccion, has been paid by the incumbent mayor to run as a nuisance candidate and to rival Dr. Jess.",
    footage: '',
    poster: 'Thumbnails/Doc Resureccion_ Gagamutin ang Bayan/Poster.png',
    banner: 'Thumbnails/Doc Resureccion_ Gagamutin ang Bayan/Banner.png',
    teaser: '',
    resolution: '4K',
    runtime: '59 mins',
  },
  {
    title: 'Anak Ka Ng',
    category: 'Theater',
    subcategory: 'VLF',
    description:
      "Pina has spent most of her life without a mother. She has learned to rely on and love only her father. But now her father is dead. Connie, her mother, came home from abroad seemingly just to attend to the details of the funeral and burial, not to grieve. Soon, Connie will leave the Philippines again. Pina has to decide: will she forgive her mother and try to salvage their relationship, or will she cast Connie completely out of her life?",
    footage: '',
    poster: 'Thumbnails/Anak Ka Ng/Poster.png',
    banner: 'Thumbnails/Anak Ka Ng/Banner.png',
    teaser: '',
    resolution: '1080p',
    runtime: '42 mins',
  },
  {
    title: 'My Boy Superman',
    category: 'Film',
    subcategory: 'Gawad Alternatibo',
    description:
      "Oyen was diagnosed with Autism Spectrum Disorder (ASD) at the age of 2. With the early diagnosis, his parents remained optimistic that love and support would help him achieve independence. However, as Oyen turns fifteen, they face the challenging realization that not all children with autism develop high-functioning skills.",
    footage: '',
    poster: 'Thumbnails/My Boy Superman/Poster.png',
    banner: 'Thumbnails/My Boy Superman/Banner.png',
    teaser: '',
    resolution: '1920p',
    runtime: '24 mins',
  },
  {
    title: 'Ang Pamilya Maguol',
    category: 'Film',
    subcategory: 'Gawad Alternatibo',
    description:
      "After the death of their beloved Grandma Gloria, a family of four is having a hard time to reconnect. At the wake, Jopet, the son, finds a letter from his dead grandmother that will lead him to a search of identity, belongingness, and family secrets…",
    footage: '',
    poster: 'Thumbnails/Ang Pamilya Maguol/Poster.png',
    banner: 'Thumbnails/Ang Pamilya Maguol/Banner.png',
    teaser: '',
    resolution: '3840p',
    runtime: '20 mins',
  },
  {
    title: "There's A Mountain Nearby and I Don't Like It",
    category: 'Film',
    subcategory: 'Gawad Alternatibo',
    description:
      "An experimental film chronicling the filmmaker’s journey in discovering himself and the decision to let people into his life as a queer individual, referencing all sides of his identity, both its freeing and once-restricting sides, both from childhood and the present.",
    footage: '',
    poster: 'Thumbnails/There_s A Mountain Nearby and I Don_t Like It/Poster.png',
    banner: 'Thumbnails/There_s A Mountain Nearby and I Don_t Like It/Banner.png',
    teaser: '',
    resolution: '1920p',
    runtime: '19 mins',
  },
  {
    title: "Sincerity Bikers Club",
    category: 'Theater',
    subcategory: 'VLF',
    description:
      "The only bikers' club of Barangay Sincerity welcomes a new member: Louella, a widow from Manila. All five original members are happy about the new addition to their club, except for one who reveals that Louella is rumored to be a drug user and that her husband was killed by the police for being a drug addict. The revelation causes dissent amongst the members. Those who fear for the club's reputation and their safety want Louella out. Some, however, feel that Louella shouldn't be punished for the tragic events of her past. All are faced with a dilemma: will they succumb to fear or will compassion win out?",
    footage: '',
    poster: 'Thumbnails/Sincerity Bikers Club/Poster.png',
    banner: 'Thumbnails/Sincerity Bikers Club/Banner.png',
    teaser: '',
    resolution: '1080p',
    runtime: '40 mins',
  },
];


export const theaters = [
    {
      title: 'Mga Eksena sa Buhay ng Kontrabida',
      category: 'Theater',
      subcategory: 'VLF',
      description:
        'Jake is a villain. He’s violent, selfish, and reckless. Unfortunately, Jake doesn’t exist in a vacuum, and his behavior has consequences. Because Jake is a villain, people around him feel threatened, and these people look for ways to solve the problem that is Jake. Part origin story, part family drama, the play is a collection of conversations heard in the vicinity of a villain.',
      footage: '',
      poster: 'Thumbnails/Mga Eksena sa Buhay ng Kontrabida/Poster.png',
      banner: 'Thumbnails/Mga Eksena sa Buhay ng Kontrabida/Banner.png',
      teaser: '',
      resolution: '1080p',
      runtime: '52 mins',
    },
    {
      title: 'Doc Resureccion: Gagamutin ang Bayan',
      category: 'Theater',
      subcategory: '',
      description:
        "Dr. Jess Resureccion is running for mayor in his poor fishing village, determined to bring real change to the place he grew up in. However, Dr. Jess’ cousin, Boy Pogi Resureccion, has been paid by the incumbent mayor to run as a nuisance candidate and to rival Dr. Jess.",
      footage: '',
      poster: 'Thumbnails/Doc Resureccion_ Gagamutin ang Bayan/Poster.png',
      banner: 'Thumbnails/Doc Resureccion_ Gagamutin ang Bayan/Banner.png',
      teaser: '',
      resolution: '4K',
      runtime: '59 mins',
    },
    {
      title: 'Anak Ka Ng',
      category: 'Theater',
      subcategory: 'VLF',
      description:
        "Pina has spent most of her life without a mother. She has learned to rely on and love only her father. But now her father is dead. Connie, her mother, came home from abroad seemingly just to attend to the details of the funeral and burial, not to grieve. Soon, Connie will leave the Philippines again. Pina has to decide: will she forgive her mother and try to salvage their relationship, or will she cast Connie completely out of her life?",
      footage: '',
      poster: 'Thumbnails/Anak Ka Ng/Poster.png',
      banner: 'Thumbnails/Anak Ka Ng/Banner.png',
      teaser: '',
      resolution: '1080p',
      runtime: '42 mins',
    },
    {
      title: "Sincerity Bikers Club",
      category: 'Theater',
      subcategory: 'VLF',
      description:
        "The only bikers' club of Barangay Sincerity welcomes a new member: Louella, a widow from Manila. All five original members are happy about the new addition to their club, except for one who reveals that Louella is rumored to be a drug user and that her husband was killed by the police for being a drug addict. The revelation causes dissent amongst the members. Those who fear for the club's reputation and their safety want Louella out. Some, however, feel that Louella shouldn't be punished for the tragic events of her past. All are faced with a dilemma: will they succumb to fear or will compassion win out?",
      footage: '',
      poster: 'Thumbnails/Sincerity Bikers Club/Poster.png',
      banner: 'Thumbnails/Sincerity Bikers Club/Banner.png',
      teaser: '',
      resolution: '1080p',
      runtime: '40 mins',
    },
  ];
  

  export const films = [
    {
      title: 'Tukso',
      category: 'Film',
      subcategory: 'Cinemalaya',
      description:
        'A young village lass is found dead. An investigator (Adel) is assigned to look into the case and gets to learn more about the girl and the people whose lives have been affected by her and her death: her father (Bal), a young architect (Carlo), a businessman (David), her childhood friend (Emer), and a widow (Fe).',
      footage: '',
      poster: 'Thumbnails/Tukso/Poster.png',
      banner: 'Thumbnails/Tukso/Banner.png',
      teaser: '',
      resolution: '720p',
      runtime: '1 hr 16 mins',
    },
    {
      title: 'Vox Populi',
      category: 'Film',
      subcategory: 'Cinemalaya',
      description:
        'Vox Populi follows a female candidate for mayor in a small town on the last day of the campaign period. To ensure her win, she will need to secure the support of voters and financiers who may have varying, and even conflicting, desires and agendas.',
      footage: '',
      poster: 'Thumbnails/Vox Populi/Poster.png',
      banner: 'Thumbnails/Vox Populi/Banner.png',
      teaser: '',
      resolution: '720p',
      runtime: '1 hr 26 mins',
    },
    {
      title: 'Backstage Pass: Life Behind the Curtains',
      category: 'Film',
      subcategory: '',
      description:
        'Directed by award-winning indie filmmaker Joseph Mangat, this 30-minute feature documentary covers the back-of-house activities of the CCP Theater Crew in lights, fly, and stage areas. Featured crew members likewise share their unique backstage stories in the film.',
      footage: '',
      poster: 'Thumbnails/Backstage Pass_ Life Behind the Curtains (Episode 1)/Poster.png',
      banner: 'Thumbnails/Backstage Pass_ Life Behind the Curtains (Episode 1)/Banner.png',
      teaser: '',
      resolution: '4K',
      runtime: '29 mins',
    },
    {
      title: 'Backstage Pass: A Portrait of a Scenic Artist',
      category: 'Film',
      subcategory: '',
      description:
        'Directed by award-winning indie filmmaker Joseph Mangat, this 30-minute feature documentary follows the day in the life of a scenic draftsman, model maker, and painter. This documentary focuses on the numerous productions that he has done and the mentees that he has mentored in the past years since the 1970s.',
      footage: '',
      poster: 'Thumbnails/Backstage Pass_ A Portrait of a Scenic Artist (Episode 2)/Poster.png',
      banner: 'Thumbnails/Backstage Pass_ A Portrait of a Scenic Artist (Episode 2)/Banner.png',
      teaser: '',
      resolution: '1920p',
      runtime: '31 mins',
    },
    {
      title: 'My Boy Superman',
      category: 'Film',
      subcategory: 'Gawad Alternatibo',
      description:
        "Oyen was diagnosed with Autism Spectrum Disorder (ASD) at the age of 2. With the early diagnosis, his parents remained optimistic that love and support would help him achieve independence. However, as Oyen turns fifteen, they face the challenging realization that not all children with autism develop high-functioning skills.",
      footage: '',
      poster: 'Thumbnails/My Boy Superman/Poster.png',
      banner: 'Thumbnails/My Boy Superman/Banner.png',
      teaser: '',
      resolution: '1920p',
      runtime: '24 mins',
    },
    {
      title: 'Ang Pamilya Maguol',
      category: 'Film',
      subcategory: 'Gawad Alternatibo',
      description:
        "After the death of their beloved Grandma Gloria, a family of four is having a hard time to reconnect. At the wake, Jopet, the son, finds a letter from his dead grandmother that will lead him to a search of identity, belongingness, and family secrets…",
      footage: '',
      poster: 'Thumbnails/Ang Pamilya Maguol/Poster.png',
      banner: 'Thumbnails/Ang Pamilya Maguol/Banner.png',
      teaser: '',
      resolution: '3840p',
      runtime: '20 mins',
    },
    {
      title: "There's A Mountain Nearby and I Don't Like It",
      category: 'Film',
      subcategory: 'Gawad Alternatibo',
      description:
        "An experimental film chronicling the filmmaker’s journey in discovering himself and the decision to let people into his life as a queer individual, referencing all sides of his identity, both its freeing and once-restricting sides, both from childhood and the present.",
      footage: '',
      poster: 'Thumbnails/There_s A Mountain Nearby and I Don_t Like It/Poster.png',
      banner: 'Thumbnails/There_s A Mountain Nearby and I Don_t Like It/Banner.png',
      teaser: '',
      resolution: '1920p',
      runtime: '19 mins',
    },
  ];

  export const ccpspecial = [
    {
      title: 'Noli Me Tangere: The TeleMovie (Episode 1: Crisostomo Ibarra)',
      category: 'CCP Specials',
      subcategory: '',
      description:
        "Eddie Romero's Noli Me Tangere mini-series, a faithful rendition of Rizal's characters and their respective tales.",
      footage: '',
      poster: 'Thumbnails/Noli Me Tangere_ The TeleMovie (Episode 1 - Crisostomo Ibarra)/Poster.png',
      banner: 'Thumbnails/Noli Me Tangere_ The TeleMovie (Episode 1 - Crisostomo Ibarra)/Banner.png',
      teaser: '',
      resolution: '720p',
      runtime: '49 mins',
    },
  ];